/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gauge.crawler.gaugefile;

import com.gauge.crawler.commons.Validator;
import java.io.File;

/**
 *
 * @author Abhay
 */
//this class will responsible for validating File path generated by FilePath class
public class FilePathValidator implements Validator {

    @Override
    public boolean isValid(Object folderPath) { // This method will validate filepath
        File file = new File((String) folderPath);
        if (file.exists()) {
            // System.out.println(file + " This file is available");
            return true;
        } else {
            // System.out.println(file + " This file is not available");
            return false;
        }

    }

}
